Makefile: Disable misleading-indentation and bool-compare warnings Generally, I prefer to keep these CFLAGS to a minimum and address any ambiguous syntax rather than ignore GCC related Werrors. In this case, all build interruptions caused by misleading-indentation and bool-compare warnings have been previously dealt with, thus I am disabling this warning to allow for proper compilation of qcacld-2.0 drivers until a more elegant soloution presents itself.
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c: In function 'i_trim':
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c:4768:4: error: this 'for' clause does not guard... [-Werror=misleading-indentation]
    for (ptr = str; i_isspace(*ptr); ptr++);
    ^~~
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c:4769:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'for'
       if (*ptr == '\0')
       ^~
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c:4777:4: error: this 'for' clause does not guard... [-Werror=misleading-indentation]
    for (; ptr != str && i_isspace(*ptr); ptr--);
    ^~~
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c:4779:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'for'
       ptr[1] = '\0';
       ^~~
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c: In function 'hdd_update_config_dat':
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c:6641:5: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
     if (ccmCfgSetInt(pHddCtx->hHal, WNI_CFG_MCAST_BCAST_FILTER_SETTING, pConfig->mcastBcastFilterSetting,
     ^~
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_cfg.c:6652:6: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
      if (ccmCfgSetInt(pHddCtx->hHal, WNI_CFG_TELE_BCN_WAKEUP_EN, pConfig->teleBcnWakeupEn,
      ^~

 drivers/staging/qcacld-2.0/CORE/UTILS/FWLOG/dbglog_host.c: In function 'dbglog_report_enable':
 drivers/staging/qcacld-2.0/CORE/UTILS/FWLOG/dbglog_host.c:1774:18: error: comparison of constant '1' with boolean expression is always false [-Werror=bool-compare]
      if (isenable > TRUE) {
                   ^

Signed-off-by: Adam Willis <return.of.octobot@gmail.com>